import Router from "express";
import { loginUser, paymentRazorpay, registerUser, userCredits, verifyRozarpay } from "../controllers/userController.js";
import userAuth from "../middleware/auth.js";
const userRouter = Router();
userRouter.post("/register", registerUser);
userRouter.post("/login", loginUser);
userRouter.get("/credits",userAuth, userCredits);
userRouter.post("/pay-razor",userAuth, paymentRazorpay);
userRouter.post("/verify-razor", verifyRozarpay);
export default userRouter;
